name: Linting
on:
  - pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  internal_investigation:
    runs-on: ubuntu-latest
    name: Internal Investigation
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby # Latest stable CRuby version
          bundler-cache: true
      - run: bundle exec rake internal_investigation

  yamllint:
    name: Yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Yamllint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_strict: true
          yamllint_format: parsable
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  mdformat:
    name: Mdformat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Mdformat
        uses: ydah/mdformat-action@main
        with:
          number: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
